#pragma once

#include <memory>
#include <string>

#include <navtk/aspn.hpp>
#include <navtk/filtering/processors/MeasurementProcessor.hpp>
#include <navtk/not_null.hpp>
#include <navtk/tensors.hpp>

namespace navtk {
namespace filtering {
/**
 * A MeasurementProcessor that uses a MeasurementPosition measurement (with lat, lon and altitude
 * position values in rad, rad, meters and covariance in the NED frame, meters) to update a Pinson15
 * error state block, whose position states are NED errors in meters. The position measurement is
 * corrected for lever arms, differenced with the raw inertial and mapped to state units
 * (meters NED) to form an error measurement which is then supplied to the filter update equations.
 */
class PinsonPositionMeasurementProcessor : public MeasurementProcessor<> {

	/* Mounting of inertial sensor relative to platform frame. Set by constructor and updatable
	 through receive_aux_data */
	aspn_xtensor::TypeMounting inertial_mount;

	/* Mounting of position sensor relative to platform frame. Set by constructor and updatable
	 through receive_aux_data */
	aspn_xtensor::TypeMounting sensor_mount;

public:
	/**
	 * Constructor.
	 *
	 * @param label Label for this processor.
	 * @param state_block_labels Labels of the set of state blocks this processor can update. The
	 * first (and usually only) label is assumed to refer to the Pinson type StateBlock. This block
	 * is required to have position errors as the first 3 states as North, East and Down errors in
	 * meters. All other block labels are effectively ignored.
	 * @param inertial_mount Mounting of inertial sensor (whose errors are estimated by the Pinson
	 * StateBlock this processor updates) relative to platform frame. If this value is time-varying
	 * it may be updated through the receive_aux_data function.
	 * @param sensor_mount Mounting of the position sensor that supplies measurements to this
	 * processor relative to the platform frame. If this value is time-varying it
	 * may be updated through the receive_aux_data() function.
	 */
	PinsonPositionMeasurementProcessor(const std::string& label,
	                                   std::vector<std::string> state_block_labels,
	                                   aspn_xtensor::TypeMounting inertial_mount,
	                                   aspn_xtensor::TypeMounting sensor_mount);

	/**
	 * Copy constructor.
	 * @param processor Processor to copy.
	 */
	PinsonPositionMeasurementProcessor(const PinsonPositionMeasurementProcessor& processor);

	/**
	 * Configures a MeasurementPosition as an error-state measurement to update NED position error
	 * states.
	 *
	 * @param measurement Measurement of type filtering::PairedPva (wrapping a MeasurementPosition),
	 * where the MeasurementPosition and paired NavSolution are synced in time, and the NavSolution
	 * is the uncorrected inertial PVA for the inertial sensor connected to the Pinson StateBlock.
	 *
	 * @param gen_x_and_p_func Function that when evaluated yields the composite estimate and
	 * covariance of all StateBlocks whose labels reside in `state_block_labels`, joined in the
	 * order that they appear.
	 *
	 * @return If \p measurement is not a filtering::PairedPva containing a MeasurementPosition,
	 * then `nullptr`. Otherwise `std::shared_ptr` to a MeasurementModel where: \n The `z` member is
	 * a 3-element Vector of NED position errors, in meters, generated by subtracting the inertial
	 * position from the measured position and converting to NED. \n `H` is a 3xN Matrix containing
	 * an identity matrix in the first 3 rows/cols and zero elsewhere, where N is the number of
	 * states referenced by the model. \n `h` is a function that pre-multiplies the Vector input by
	 * `H` and returns the result \n and `R` is a 3x3 measurement covariance extracted directly from
	 * the MeasurementPosition contained in measurement.
	 */
	std::shared_ptr<StandardMeasurementModel> generate_model(
	    std::shared_ptr<aspn_xtensor::AspnBase> measurement,
	    GenXhatPFunction gen_x_and_p_func) override;

	/**
	 * Accepts aux data related to sensor mountings; ignores all other types.
	 *
	 * @param aux_data AspnBaseVector containing a `shared_ptr` to aspn_xtensor::MetadataGeneric,
	 * which in turn contains an aspn_xtensor::TypeMounting. If the metadata description contains
	 * this processor's label, then the mounting is assigned to the position sensor. If the
	 * description matches the Pinson label (the first element of `state_block_labels`), then it is
	 * assigned to the inertial. Otherwise it is ignored.
	 */
	void receive_aux_data(const AspnBaseVector& aux_data) override;

	/**
	 * Generate a clone of this instance.
	 *
	 * @return A copy of this MeasurementProcessor.
	 */
	not_null<std::shared_ptr<MeasurementProcessor<>>> clone() override;
};
}  // namespace filtering
}  // namespace navtk
