#pragma once

#include <memory>

#include <navtk/geospatial/detail/custom_deleters.hpp>

// Forward-declares because the GDAL headers are not reliably available at time of inclusion.
class GDALDataset;
class OGRCoordinateTransformation;
class OGRSpatialReference;

namespace navtk {
namespace geospatial {
namespace detail {

/**
 * @param dataset A GDAL object generated by opening a data file.
 *
 * @return The reference frame in \p dataset .
 */
OGRSpatialReference import_frame_from_dataset(GDALDataset& dataset);

/**
 * @return A GDAL object containing the WGS84 reference frame.
 */
OGRSpatialReference import_frame_from_wgs84();

/**
 * @param dataset A GDAL object generated by opening a data file.
 *
 * @return A unique pointer with a custom deleter to a transformation which converts coordinates
 * from the WGS84 frame to the dataset's map frame.
 */
std::unique_ptr<OGRCoordinateTransformation, TransformDelete> create_wgs84_to_map_transformation(
    GDALDataset& dataset);

/**
 * @param dataset A GDAL object generated by opening a data file.
 *
 * @return A unique pointer with a custom deleter to a transformation which converts coordinates
 * from the dataset's map frame to the WGS84 frame.
 */
std::unique_ptr<OGRCoordinateTransformation, TransformDelete> create_map_to_wgs84_transformation(
    GDALDataset& dataset);

}  // namespace detail
}  // namespace geospatial
}  // namespace navtk
