find_package(PkgConfig)
pkg_check_modules(PC_navtk REQUIRED navtk)
if(PC_navtk_FOUND)
    set(navtk_LIBRARIES "${PC_navtk_LIBRARIES}")
    set(navtk_INCLUDE_DIRS "${PC_navtk_INCLUDE_DIRS}")
    set(navtk_DEFINITIONS "${PC_navtk_CFLAGS_OTHER}")
    set(navtk_LIBRARY_DIRS "${PC_navtk_LIBRARY_DIRS}")
    return()
endif()
